### ISSUE TITLE
Headless environment issue

### ISSUE THREAD

**Issue by Skeen** [mappum/electron-eval#29]
Running the example code;
```
var electronEval = require('electron-eval')
 
// create new electron instance 
var daemon = electronEval()
 
daemon.eval('JSON.stringify(window.location.href)', function (err, res) {
  console.log(err, res)
  // prints 'null file:///Users/mappum/Projects/electron-eval/index.html' 
})
```
In a headless environment (inside `docker run node:argon`) yields;
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)
```
At version `0.7.6`.

**Comment by mappum** [comment]
Interesting, I'd like it to detect headless environments by default and attempt to run `xvfb` (currently it tries it whenever `process.platform` is `linux`). If for some reason `xvfb` is not being started, you could try using the HEADLESS=1 env var, or the `{ headless: true }` option when you create your daemon.

Although those are just quick fixes so I'd like to be able to detect the headless environment in your setup automatically.

**Comment by Skeen** [comment]
Hi, `xvfb` is indeed being started up;
```
root       715  0.0  1.4 152296 14892 ?        S    17:55   0:00 Xvfb :99
```
So I do not thing this is the issue.

**Comment by Skeen** [comment]
I believe it's the same issue as [this](https://github.com/feross/webtorrent-hybrid/issues/29) on webtorrent-hybrid.

**Comment by Skeen** [comment]
I have made an image with the faulty configuration;
```
docker run -it skeen/testimage
```
Which will execute the test code, and fail, or;
```
docker run -it skeen/testimage bash
```
To poke around, the code is contained within `/root/app/`

NOTE: I have added a print statement within the `electron-eval` library, as I'm trying to debug the issue.

**Comment by Skeen** [comment]
Update: The exception is thrown even with just this code;
```
var electronEval = require('electron-eval')
var daemon = electronEval()
```

**Comment by mappum** [comment]
Awesome, thank you! I'll mess around with it when I get home in a few hours.

**Comment by mappum** [comment]
I believe the EPIPE happening from the line where the `opts` object is
being written to the daemon's stdin stream, because the electron process is
not being started properly.

**Comment by Skeen** [comment]
Yes, this seems like a likely explaination; indeed because the issue is somewhat random;
```
root@103c22db063f:~/app# node app.js 
_startXvfb
_eval
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)
```
Running the same command again yields;
```
root@103c22db063f:~/app# node app.js 
_startXvfb
_eval
keepalive
```

**Comment by Skeen** [comment]
I'm testing with `0.7.10`; I can confirm that the EPIPE error is gone, and that an `Xvfb` instance is started (`:166` now).

However the process hangs, the callback at: [Line 107-117](https://github.com/mappum/electron-eval/blob/master/src/index.js#L107-L117) is never called, and thus `opts` are never written.

**Comment by Skeen** [comment]
I have updated my docker test image; `skeen/testimage:0.0.1`, running it yields;
```
root@89aea2868f6f:~/app# node app.js 
constructor
_startHeadless
constructor done
_startElectron
_startElectron done
_startHeadless done
```
At which point the application hangs. I'd expect to see the; `this.stdout.once` debug message, indicating that the callback for this has been fired.

**Comment by Skeen** [comment]
The `node:argon` base image did not fulfill several dependencies of `electron`;
```
apt-get install -y libnss3 libgconf2-4 libnotify4 libgtk2.0-0
```
However the issue does still seem to persist, only I was able to get electron to start.

**Comment by Skeen** [comment]
Correction; With the additional above dependencies installed, the example runs :+1:

**Comment by Skeen** [comment]
Output (with additional debug statements);
```
root@0317db9b51b2:~/app# node app.js 
Xlib:  extension "RANDR" missing on display ":114".

(electron) ipc module is deprecated. Use require("electron").ipcMain instead.

"starting"

Xlib:  extension "RANDR" missing on display ":114".

libGL error: No matching fbConfigs or visuals found

libGL error: failed to load driver: swrast

(electron) loadUrl is deprecated. Use loadURL instead.

"ready"

["1",{"res":"\"file:///root/app/node_modules/electron-eval/app/index.html\""}]

null '"file:///root/app/node_modules/electron-eval/app/index.html"'
```

**Comment by mappum** [comment]
Interesting, so does that mean Electron is showing an error that doesn't get exposed to the node process? (They do show fatal errors as a popup dialog for some reason). I guess that's another bug, to somehow get those errors if possible and emit them in node.

BTW, glad you got it working, I was going to say I was out of ideas of what could be wrong :P

**Comment by mappum** [comment]
Thanks for the help in testing this! :smile:

**Comment by Skeen** [comment]
The way I debugged this, was checking the `stderr` from the `child` argument in the callback fro `headless`, and from `electron`.

By doing this I got errors alike;
```
/root/app/node_modules/electron-eval/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```
Maybe it'd be neat to check if there's anything on the error streams, or even output them to console / callback :)

**Comment by mappum** [comment]
Ah good point. If all stderr output is actually errors then I could make it emit stderr messages as `error` events.

**Comment by Skeen** [comment]
```
    key: '_startHeadless',
    value: function _startHeadless(cb) {
      var _this3 = this;

      if (headless == null) {
        return cb(new Error('Could not load "headless" module'));
      }
      headless(function (err, child, display) {
        if (err) {
          var err2 = new Error('Could not start Xvfb: "' + err.message + '". \n' + 'The "xvfb" package is required to run "electron-eval" on Linux. ' + 'Please install it first ("sudo apt-get install xvfb").');
          return cb(err2);
        }

      // Here: Output from the headless child process
      child.stdout.on('data', function(data)
      {
        console.log(data.toString());
      });
      child.stderr.on('data', function(data)
      {
        console.log(data.toString());
      });
         
        process.on('exit', function () {
          return child.kill();
        });
        _this3.xvfb = child;
        _this3.xDisplay = ':' + display;
        cb(null);
      });
    }
```
And:
```
      this.child = spawn(electron, [daemonMain], { env: env });
      this.child.on('error', function (err) {
        return _this4.emit('error', err);
      });

      // Here: Output from the headless child process
      this.child.stdout.on('data', function(data)
      {
        console.log(data.toString());
      });
      this.child.stderr.on('data', function(data)
      {
        console.log(data.toString());
      });

      this.stdout = this.child.stdout.pipe(json.Parser());
```

**Comment by Skeen** [comment]
That would make sense; however it does not seem to be all errors; this is the `stderr` output from the test program:
```
root@0317db9b51b2:~/app# node app.js 
Xlib:  extension "RANDR" missing on display ":114".

(electron) ipc module is deprecated. Use require("electron").ipcMain instead.

Xlib:  extension "RANDR" missing on display ":114".

libGL error: No matching fbConfigs or visuals found

libGL error: failed to load driver: swrast

(electron) loadUrl is deprecated. Use loadURL instead.
```
I'd generally classify these merely as warnings.

**Comment by Skeen** [comment]
It's just some deprecation warnings form `electron` and missing extenions on the `Xvfb` (letting us know, that we can't change the resolution; meh).

**Comment by mappum** [comment]
Got it. I guess the best way is to just emit 'stderr' events, and if
Electron isn't working, the user can use those events for debugging.

**Comment by mappum** [comment]
Or of course they could just use the stderr stream directly.

**Comment by Skeen** [comment]
That'd work; only I actually think the X-related errors are from the `headless` child; as such the error stream from electron would be;
```
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
(electron) loadUrl is deprecated. Use loadURL instead.
```
Fixing these deprecation warning, would allow you to use the electron process's stderr as error events?

**Comment by Skeen** [comment]
Anyhow; this issue is solved and closed, and I bet `webtorrent-hybrid` works as well :)
- Even though it may require the above mentioned libraries as well, depending on the underlying system configuration.
