### ISSUE TITLE
Handle child process crashing

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/electron-eval#42]
The context for this is that I've been trying to use electron-webrtc on a machine running Amazon EC2 Linux. The electron process is crashing because it can't find a library. However, this doesn't result in electron-eval emitting an error.

I think that I can fix this by listening for the `close` event from the child process and then emitting an `error` event if the status code is not 0. What's a good way to display the error? We could just pipe stderr from the child process to stderr for the main Node JS process for starters.

**Comment by paulkernfeld** [comment]
I made PR #43 for this.

**Comment by mappum** [comment]
#43 was merged.
