### ISSUE TITLE
Support proxy settings or run code in main process

### ISSUE THREAD

**Issue by yciabaud** [mappum/electron-eval#44]
I am trying to add proxy support when using electron-wrtc (in webtorrent) but I don't think it's possible right now with electron-eval.

I believe it could be useful to add a way to set the settings or event better to allow running code in the electron main process.

Maybe we could add a new function to eval code in the main process and wrap the code in a structure like : `{ target: "renderer|main", code: "..." }` in order to make the difference in the deamon.

What do you think ? I can send a PR in this way if you like.

**Comment by mappum** [comment]
Merged.
