### ISSUE TITLE
Parser error in electron-eval

### ISSUE THREAD

**Issue by ipsBruno** [mappum/electron-eval#50]
Hello!

I get this error on use electron-webrtc in **webtorrent-hybrid**

![teste](https://cloud.githubusercontent.com/assets/6839604/17968758/ea33cfd4-6aa4-11e6-9317-a4c91cd1d70e.png)

Aparently, is an error in **newline-json** dependencie. code:

> 
> Parser.prototype._transform = function(chunk, encoding, cb) {
>   this._buffer += this._decoder.write(chunk);
>   var lines = this._buffer.split(/\r?\n/);
>   this._buffer = lines.pop();
>   for (var l = 0; l < lines.length; l++) {
>     var line = lines[l];
>     try {
>       var obj = JSON.parse(line);
>       this.push((obj === null || obj === undefined) ? false : obj);
>     } catch (err) {
>       var context = lines.slice(l).join('\n')+'\n'+this._buffer;
>       **er = new Error(err.message+' in '+JSON.stringify(context));
>       this.emit('error', er);**
>       return;
>     }
>   }
>   cb();
> };
> 

My O.S is Windows Server 2008. Is compatible?

@mappum

**Comment by mappum** [comment]
Should be fixed as of `0.9.2`.
